// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFamilyMapAPI.Core.Data;

#nullable disable

namespace open_family_map.Migrations
{
    [DbContext(typeof(OpenFamilyMapContext))]
    partial class OpenFamilyMapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.LocationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("LocationDetail");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DisplayName = "Admin User",
                            Login = "admin",
                            Password = "pCNO/Dkf+OKKIzyJjen5sA==",
                            UpdatedDate = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.LocationDetail", b =>
                {
                    b.HasOne("OpenFamilyMapAPI.Entities.User", null)
                        .WithMany("LocationHistory")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.User", b =>
                {
                    b.Navigation("LocationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
