// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenFamilyMapAPI.Core.Data;

#nullable disable

namespace open_family_map.Migrations
{
    [DbContext(typeof(OpenFamilyMapContext))]
    [Migration("20251125233843_RefreshTokens")]
    partial class RefreshTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.LocationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("AltitudeMeters")
                        .HasColumnType("double");

                    b.Property<double?>("BearingAccuracyDegrees")
                        .HasColumnType("double");

                    b.Property<double?>("BearingDegrees")
                        .HasColumnType("double");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("ElapsedRealtimeSinceBoot")
                        .HasColumnType("time(6)");

                    b.Property<int?>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<double?>("HorizontalAccuracyMeters")
                        .HasColumnType("double");

                    b.Property<bool?>("IsMock")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<DateTime>("LocationUpdateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawProvider")
                        .HasColumnType("longtext");

                    b.Property<double?>("SpeedAccuracyMetersPerSecond")
                        .HasColumnType("double");

                    b.Property<double?>("SpeedMetersPerSecond")
                        .HasColumnType("double");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("VerticalAccuracyMeters")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("UserId");

                    b.ToTable("LocationDetails");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.RefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.LocationDetail", b =>
                {
                    b.HasOne("OpenFamilyMapAPI.Entities.User", "User")
                        .WithMany("LocationHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.RefreshToken", b =>
                {
                    b.HasOne("OpenFamilyMapAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OpenFamilyMapAPI.Entities.User", b =>
                {
                    b.Navigation("LocationHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
